include: package:lints/recommended.yaml

linter:
  rules:
    prefer_single_quotes: true
    unawaited_futures: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: false  # Allowed for example code
