name: weebi_barcode_dart
description: "Core barcode detection library using embedded YOLO neural network. Provides low-level FFI interface to Rust-based barcode detection with support for multiple image formats and high accuracy detection."
version: 1.0.0
homepage: https://github.com/weebi-com/weebi_barcode_dart
repository: https://github.com/weebi-com/weebi_barcode_dart
issue_tracker: https://github.com/weebi-com/weebi_barcode_dart/issues

environment:
  sdk: ^3.0.0

dependencies:
  # FFI for native library integration
  ffi: ^2.0.1
  
  # Image processing utilities
  image: ^4.0.17

dev_dependencies:
  test: ^1.21.0
  lints: ^4.0.0
  # Path utilities for tests
  path: ^1.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
